spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatroom?serverTimezone=UTC
    username: root
    password: 13456191231sh
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    # 开启rest风格请求
    hiddenmethod:
      filter:
        enabled: true
    # 定义匹配静态资源路径
    static-path-pattern: /static/**

  # 开启页面热部署
  thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix: .html

  # 开启类加载器热部署
  devtools:
    restart:
      enabled: false

server:
  port: 5000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:mapper/*.xml

mybatis:
  # mapper映射文件位置（用注解开发则不需要映射文件）
  mapper-locations: classpath:mapper/*.xml
  # 全局配置，可代替全局配置文件
  configuration:
    # 开启下划线转驼峰命名规则
    map-underscore-to-camel-case: true
